version: '3.8'

services:
  # Flask Application Container
  flask_app:
    image: manavm18/flask:latest
    build: .
    container_name: flask_app 
    ports:
      - "5001:5000"  # Expose Flask app on host port 5001
    depends_on:
      - db  # Ensure the database container is up before starting Flask
    environment:
      - DATABASE_URL=postgresql://admin:admin@localhost:5432/mydb
      - DB_HOST=db

  # pgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    container_name: flask_pgadmin
    ports:
      - "5050:80"  # Expose port 5050 for pgAdmin web UI
    depends_on:
      - db

  # PostgreSQL Database Container
  db:
    image: postgres:13
    container_name: flask_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data on the host

# Define a named volume for PostgreSQL data persistence
volumes:
  db_data:

networks:
  flask_network:
    driver: bridge