version: '3.8'

services:
  # Flask Application Container
  flask_app:
    image: manavm18/flask:new
    build: .
    ports:
      - "5001:5000"  # Expose Flask app on host port 5001
    depends_on:
      - db  # Ensure the database container is up before starting Flask
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/mydb
      - DB_HOST=db
    deploy:
      replicas: 2  # Scale to 2 replicas for load balancing
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - flask_net

  # pgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # Expose port 5050 for pgAdmin web UI
    depends_on:
      - db
    deploy:
      replicas: 1  # Typically only one instance of pgAdmin is needed
      restart_policy:
        condition: on-failure
    networks:
      - flask_net

  # PostgreSQL Database Container
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data on the host
    deploy:
      placement:
        constraints: [node.role == manager]  # Place on manager nodes (optional)
      restart_policy:
        condition: on-failure
    networks:
      - flask_net

# Define a named volume for PostgreSQL data persistence
volumes:
  db_data:

# Define an overlay network for Swarm mode
networks:
  flask_net:
    driver: overlay
